import { z } from 'zod';
import '@/lib/github/globals';
import { getHeadSha, createBranch, commitMultipleFiles, createPR } from '@/lib/github/operations';
import type { PipelineConfig } from '@/lib/agents/pipeline-generator';

// Prevent Next.js from caching this route
export const dynamic = 'force-dynamic';

/**
 * Request body schema for PR creation
 */
const createPRRequestSchema = z.object({
  type: z.enum(['pipeline', 'remediation']),
  owner: z.string(),
  repo: z.string(),
  filePath: z.string(),       // original CALM file path (for remediation)
  fileSha: z.string(),        // current SHA of CALM file (for remediation)
  defaultBranch: z.string(),  // base branch for PR
});

/**
 * Map GitHub HTTP status codes to descriptive user-facing messages.
 */
function mapGitHubError(statusCode: number, raw: string): string {
  if (statusCode === 401 || statusCode === 403) {
    return 'Authentication failed. Check GITHUB_TOKEN permissions (needs "repo" scope).';
  }
  if (statusCode === 404) {
    return 'Repository or branch not found.';
  }
  if (statusCode === 422) {
    return 'GitHub rejected the request — branch may already exist or permissions insufficient.';
  }
  return `GitHub API error (${statusCode}): ${raw}`;
}

/**
 * Build pipeline files array from a PipelineConfig result.
 *
 * Files committed to the source repo:
 *   .github/workflows/calmguard-ci.yml     — main CI/CD workflow
 *   .github/{tool.name}.yml               — security scanning tool configs
 *   terraform/main.tf or cloudformation/template.yaml — IaC
 */
function buildPipelineFiles(
  pipeline: PipelineConfig,
): Array<{ path: string; content: string }> {
  const files: Array<{ path: string; content: string }> = [];

  // Main GitHub Actions workflow
  files.push({
    path: '.github/workflows/calmguard-ci.yml',
    content: pipeline.githubActions.yaml,
  });

  // Security scanning tool configs
  for (const tool of pipeline.securityScanning.tools) {
    files.push({
      path: `.github/${tool.name}.yml`,
      content: tool.config,
    });
  }

  // Infrastructure as Code
  if (pipeline.infrastructureAsCode.provider === 'terraform') {
    files.push({
      path: 'terraform/main.tf',
      content: pipeline.infrastructureAsCode.config,
    });
  } else {
    files.push({
      path: 'cloudformation/template.yaml',
      content: pipeline.infrastructureAsCode.config,
    });
  }

  return files;
}

/**
 * Build the PR body Markdown for a pipeline PR.
 */
function buildPipelinePRBody(
  pipeline: PipelineConfig,
  files: Array<{ path: string; content: string }>,
): string {
  const fileList = files
    .map((f) => {
      if (f.path === '.github/workflows/calmguard-ci.yml') {
        return `- \`${f.path}\` — CI/CD workflow with build, test, security scan, deploy stages`;
      }
      const tool = pipeline.securityScanning.tools.find(
        (t) => `.github/${t.name}.yml` === f.path,
      );
      if (tool) {
        return `- \`${f.path}\` — ${tool.description}`;
      }
      const iac = pipeline.infrastructureAsCode;
      return `- \`${f.path}\` — Infrastructure as Code (${iac.provider})`;
    })
    .join('\n');

  const toolList = pipeline.securityScanning.tools
    .map((t) => `- **${t.name}**: ${t.description}`)
    .join('\n');

  const recList = pipeline.recommendations
    .map((r) => `- [${r.priority}] ${r.category}: ${r.recommendation}`)
    .join('\n');

  return [
    '## CALMGuard Pipeline Artifacts',
    '',
    'Generated by [CALMGuard](https://github.com/finos-labs/dtcch-2026-opsflow-llc) compliance analysis.',
    '',
    '### Summary',
    pipeline.summary,
    '',
    '### Files Added',
    fileList,
    '',
    '### Security Scanning Tools',
    toolList,
    '',
    '### Recommendations',
    recList,
    '',
    '---',
    '*Generated by CALMGuard CALM-native compliance platform*',
  ].join('\n');
}

/**
 * POST /api/github/create-pr
 *
 * Creates a GitHub PR with generated pipeline artifacts or compliance remediation.
 * Streams SSE progress events during the process.
 *
 * Request body: CreatePRRequest
 * Response: text/event-stream — sequence of SSE frames:
 *   data: { type: "step", step: string }\n\n
 *   data: { type: "done", prUrl, prNumber, branchName, fileCount }\n\n
 *   data: { type: "error", message: string }\n\n
 */
export async function POST(req: Request): Promise<Response> {
  // 1. Validate request body
  let bodyRaw: unknown;
  try {
    bodyRaw = await req.json();
  } catch {
    return Response.json({ error: 'Invalid JSON in request body' }, { status: 400 });
  }

  const bodyResult = createPRRequestSchema.safeParse(bodyRaw);
  if (!bodyResult.success) {
    return Response.json(
      { error: 'Invalid request body', issues: bodyResult.error.issues },
      { status: 400 },
    );
  }

  const { type, owner, repo, filePath, fileSha, defaultBranch } = bodyResult.data;

  // 2. Remediation not yet implemented (Plan 03)
  if (type === 'remediation') {
    return Response.json(
      { error: 'Remediation PR not yet implemented' },
      { status: 501 },
    );
  }

  // 3. Require GITHUB_TOKEN for write operations
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    return Response.json(
      {
        error: 'GITHUB_TOKEN is not configured. Set it in your environment to enable PR generation.',
      },
      { status: 503 },
    );
  }

  // 4. Stream pipeline PR creation steps as SSE
  const encoder = new TextEncoder();

  const stream = new ReadableStream({
    async start(controller) {
      const emit = (data: unknown) => {
        controller.enqueue(encoder.encode(`data: ${JSON.stringify(data)}\n\n`));
      };

      try {
        // Step 1: Get HEAD SHA
        emit({ type: 'step', step: 'Getting HEAD SHA...' });
        const headSha = await getHeadSha(owner, repo, defaultBranch, token).catch((err: unknown) => {
          const msg = err instanceof Error ? err.message : String(err);
          // Check for common HTTP errors in the message
          if (msg.includes('(401)') || msg.includes('(403)')) {
            throw new Error(mapGitHubError(403, msg));
          }
          if (msg.includes('(404)')) {
            throw new Error(mapGitHubError(404, msg));
          }
          throw new Error(msg);
        });

        // Step 2: Create branch
        const branchName = `calmguard/pipeline-${Date.now()}`;
        emit({ type: 'step', step: 'Creating branch...' });
        await createBranch(owner, repo, branchName, headSha, token).catch((err: unknown) => {
          const msg = err instanceof Error ? err.message : String(err);
          if (msg.includes('(422)')) {
            throw new Error(mapGitHubError(422, msg));
          }
          throw new Error(msg);
        });

        // Step 3: Commit pipeline artifacts
        emit({ type: 'step', step: 'Committing pipeline artifacts...' });

        const pipeline = globalThis.__lastPipelineResult;
        if (!pipeline) {
          throw new Error(
            'Pipeline analysis results not available. Run analysis first.',
          );
        }

        const files = buildPipelineFiles(pipeline);
        await commitMultipleFiles(
          owner,
          repo,
          branchName,
          files,
          'chore: add CALMGuard compliance pipeline artifacts',
          headSha,
          token,
        );

        // Step 4: Open pull request
        emit({ type: 'step', step: 'Opening pull request...' });
        const prBody = buildPipelinePRBody(pipeline, files);
        const { html_url: prUrl, number: prNumber } = await createPR(
          owner,
          repo,
          branchName,
          defaultBranch,
          'chore: add CALMGuard compliance pipeline',
          prBody,
          token,
        );

        // Emit done — client uses this to update PR card state
        emit({
          type: 'done',
          prUrl,
          prNumber,
          branchName,
          fileCount: files.length,
          // filePath and fileSha are included for completeness; unused by pipeline PR
          filePath,
          fileSha,
        });
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        emit({ type: 'error', message });
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      'Content-Type': 'text/event-stream; charset=utf-8',
      'Cache-Control': 'no-cache, no-transform',
      'Connection': 'keep-alive',
    },
  });
}
